namespace TeamSpeak3QueryApi.Net.ClientQuery.Enum
{
    public enum ServerVariable
    {
        Name,
        Platform,
        Version,
        Created,
        CodecEncryptionMode,
        DefaultServerGroup,
        DefaultChannelGroup,
        HostbannerUrl,
        HostbannerGfxUrl,
        HostbannerGfxInterval,
        PrioritySpeakerDimmModificator,
        Id,
        HostbuttonTooltip,
        HostbuttonUrl,
        HostbuttonGfxUrl,
        NamePhonetic,
        IconId,
        Ip,
        AskForPrivilegekey,
        HostbannerMode,

        // Unsupported as of 2021-02-03
        // Clientsonline,
        // Channelsonline,
        // Uptime,
        // FlagPassword,
        // DefaultChannelAdminGroup,
        // MaxDownloadTotalBandwidth,
        // MaxUploadTotalBandwidth,
        // ComplainAutobanCount,
        // ComplainAutobanTime,
        // ComplainRemoveTime,
        // MinClientsInChannelBeforeForcedSilence,
        // AntifloodPointsTickReduce,
        // AntifloodPointsNeededCommandBlock,
        // AntifloodPointsNeededIpBlock,
        // ClientConnections,
        // QueryClientConnections,
        // Queryclientsonline,
        // DownloadQuota,
        // UploadQuota,
        // MonthBytesDownloaded,
        // MonthBytesUploaded,
        // TotalBytesDownloaded,
        // TotalBytesUploaded,
        // Port,
        // Autostart,
        // MachineId,
        // NeededIdentitySecurityLevel,
        // LogClient,
        // LogQuery,
        // LogChannel,
        // LogPermissions,
        // LogServer,
        // LogFiletransfer,
        // MinClientVersion,
        // ReservedSlots,
        // TotalPacketlossSpeech,
        // TotalPacketlossKeepalive,
        // TotalPacketlossControl,
        // TotalPacketlossTotal,
        // TotalPing,
        // WeblistEnabled
    }
}
